name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out a bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Was there an error message? Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: error-input
    attributes:
      label: Which input causes the bug?
      description: What was your input?
      placeholder: Tell us what you typed!
      value: "ubib |find|sc|a| Author Name"
    validations:
      required: true      
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of µBib are you running?
      options:
        - 1.0.0
    validations:
      required: true
